apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].rules
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].rules
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/knative-serving/overlays/kind
    repoURL: https://github.com/dpoulopoulos/kserve-in-kind
    targetRevision: feature-argocd
  syncPolicy:
    automated: {}