apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kserve
  namespace: metallb-system
spec:
  addresses:
  - 172.18.100.0/24

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kserve
  namespace: metallb-system
spec:
  ipAddressPools:
  - kserve