apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- gateway.yaml
- virtualservice.yaml
- ../../base

patches:
  - path: patches/insecure.yaml
  - path: patches/noredirect.yaml